class Strings {
  Strings._();
  static const String app_name = 'Single Screen UI';
  static const String bank_transfer = 'Bank Transfer';
  static const String en = 'EN';
  static const String inr = 'INR';
  static const String aed = 'AED';
  static const String card_middle_text = '1 AED = 20.35 INR';
  static const String tips = 'Tips';
  static const String set_rate_alerts = 'Set Rate Alerts';
  static const String rates_warning = '* Rates are indicative and may vary';
  static const String bank = 'Bank';
  static const String transfer = 'Transfer';
  static const String cash = 'Cash';
  static const String payouts = 'Payouts';
  static const String client_wallet = 'Client Wallet';
  static const String branches = 'Branches';
  static const String more = 'More';
  static const String help = 'Help';
  static const String client = 'Client';
  static const String logo = 'Logo';
  static const String track = 'Track';
  static const String show_more = 'Show more';
  static const String exclusive_offers = 'Exclusive Offers';
  static const String you_send = 'You Send';
  static const String they_receive = 'They Receive';
  static const String amount = '00.00';
  static const String bottomCardText1 = 'Shop & Earn';
  static const String bottomCardText2 = '15% OFF on your bill';
  static const String bottomCardText3 = 'Use Promo Code: SHOP15';
}
